export const DUMMY = `dummy`;
export const GOT_IT_NEXT = `Got it, next!`;
export const LEVEL = `Level:`;
export const MAIN_CALL_TO_ACTION = `Start with 10 phrases!`;
export const MISSING_LANGUAGE_OPTIONS = `Select language options.`;
export const REPEAT = `Repeat`;
export const SHOW_ANSWER = `Show answer`;
export const SIGNUP_CALL_TO_ACTION = `Signup to get unique phrases each time. It's FREE`;
export const SITE_MOTTO = `Learn common daily phrases fast`;
